# Generated by Django 4.2 on 2023-05-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=100)),
                ('fav_zone', models.CharField(max_length=100)),
                ('image_description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='warcraftApp/files/covers')),
            ],
        ),
    ]
